apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenantops-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenantops-db
  template:
    metadata:
      labels:
        app: tenantops-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}:{{ .Values.db.tag }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.env.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: {{ .Values.db.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.env.POSTGRES_PASSWORD }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: tenantops-db-pvc
